name: GitHub Actions Publish Npm

run-name: ${{ github.actor }} Commit Messsage ğŸš€

permissions:
  contents: read

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - dev
      - lihaichao110-CICD

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install-yarn
        run: |
          npm install -g yarn
          yarn config set "strict-ssl" false -g
          yarn config set "sass_binary_site" https://npm.taobao.org/mirrors/node-sass/ -g

      - name: Install Pyenv
        run: |
          curl -fsSL https://pyenv.run | bash
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc
          source ~/.bashrc
          # ä½¿ç¯å¢ƒå˜é‡ç”Ÿæ•ˆ
          # æ£€æŸ¥æ˜¯å¦ç”Ÿæ•ˆ
          pyenv versions

      - name: install-python
        run: |
          pyenv install 2.7.18
          pyenv global 2.7.18
          python --version

      - name: deps-init
        run: yarn setup

      - name: lint
        run: yarn lint

      - name: build-ci
        run: yarn build:ci

      - name: publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

