name: GitHub Actions Publish Npm

run-name: ${{ github.actor }} Commit Messsage ğŸš€

permissions:
  contents: read

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - dev
      - lihaichao110-CICD

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install-yarn
        run: |
          npm install -g yarn
          yarn config set "strict-ssl" false -g
          yarn config set "sass_binary_site" https://npm.taobao.org/mirrors/node-sass/ -g

      # - name: Install Pyenv
      #   run: |
      #     curl -fsSL https://pyenv.run | bash
      #     echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $GITHUB_ENV
      #     echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
      #     echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV
      #     # ä½¿ç¯å¢ƒå˜é‡ç”Ÿæ•ˆ
      #     # æ£€æŸ¥æ˜¯å¦ç”Ÿæ•ˆ
      #     echo pyenv versions
      #     pyenv install 2.7.18
      #     pyenv global 2.7.18

      - name: install-python
        uses: gabrielfalcao/pyenv-action@v17
        with:
          default: 2.7.18
        # run: |
        #   # pyenv install 2.7.18
        #   # pyenv global 2.7.18
        #   python --version

      - name: deps-init
        run: |
          python --version
          yarn setup

      - name: lint
        run: yarn lint

      - name: build-ci
        run: yarn build:ci

      - name: publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

