name: GitHub Actions Publish Npm

run-name: ${{ github.actor }} Commit Messsage ðŸš€

permissions:
  contents: read
  
on:
  workflow_dispatch:

  push:
    branches:
      - master
      - dev
      - lihaichao110-CICD
# env:
#   TEST: 'https://github.com/lihaichao110/hui-design'
#   REPO_NAME: 'https://github.com/lihaichao110/hui-design'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.fork }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: |
          echo: github
          npm install -g yarn
          yarn config set "strict-ssl" false -g
          yarn config set "sass_binary_site" https://npm.taobao.org/mirrors/node-sass/ -g

      - name: Install Python
        uses: gabrielfalcao/pyenv-action@v17
        with:
          default: 2.7.18

      - name: Init
        run: |
          python --version
          yarn setup

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build:ci

      - name: Publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

